### ISSUE TITLE
[BUG] SideJITServer --pair issue

### ISSUE THREAD

**Issue by matt7570** [SideStore/SideStore#774]
### Describe the bug

I'm not being able to pair sideitserver on iPhone 18.

```
PS D:\PC\iOS\JIT\SideJITServer-main> SideJITServer --pair
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:00000000000000000000000000 VERSION:18.0.1 TYPE:iPhone11,8 PAIRED:True>]
Continue? [y/N]: y
Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 441, in request
    self.endheaders()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1035, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 279, in connect
    self.sock = self._new_conn()
                ~~~~~~~~~~~~~~^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 214, in _new_conn
    raise NewConnectionError(
        self, f"Failed to establish a new connection: {e}"
    ) from e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000024D8172DFD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49151): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024D8172DFD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\pymobiledevice3\tunneld.py", line 506, in _list_tunnels
    resp = requests.get(f'http://{tunneld_address[0]}:{tunneld_address[1]}')
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=49151): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024D8172DFD0>: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Scripts\SideJITServer.exe\__main__.py", line 7, in <module>
    sys.exit(start_server())
             ~~~~~~~~~~~~^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\SideJITServer\__init__.py", line 273, in start_server
    refresh_devs(show_installed)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\SideJITServer\__init__.py", line 127, in refresh_devs
    for dev in get_tunneld_devices():
               ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\pymobiledevice3\tunneld.py", line 486, in get_tunneld_devices
    return get_asyncio_loop().run_until_complete(async_get_tunneld_devices(tunneld_address))
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\pymobiledevice3\tunneld.py", line 480, in async_get_tunneld_devices
    tunnels = _list_tunnels(tunneld_address)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\pymobiledevice3\tunneld.py", line 509, in _list_tunnels
    raise TunneldConnectionError()
pymobiledevice3.exceptions.TunneldConnectionError
C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\websockets\legacy\__init__.py:6: DeprecationWarning: websockets.legacy is deprecated; see https://websockets.readthedocs.io/en/stable/howto/upgrade.html for upgrade instructions
  warnings.warn(  # deprecated in 14.0 - 2024-11-09
C:\Users\Matt\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py:16: DeprecationWarning: websockets.server.WebSocketServerProtocol is deprecated
  from websockets.server import WebSocketServerProtocol
INFO:     Started server process [5744]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)



```

### Instructions to reproduce

Use the "SideJITServer --pair" command

### What version of SideStore are you using?

0.5.8

**Comment by romeomogus** [comment]
Type this while inside venv: "pip3 install ipsw_parser==1.3.4", then try again
